// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuestionsAndAnswers.DataLayer.Repository;

#nullable disable

namespace QuestionsAndAnswers.DataLayer.Migrations
{
    [DbContext(typeof(ChatBotContext))]
    [Migration("20240209065658_QuestionsAnswers")]
    partial class QuestionsAnswers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuestionsAndAnswers.DataLayer.Models.QuestionsAnswers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SoftwareNameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareNameId");

                    b.ToTable("QuestionsAnswers");
                });

            modelBuilder.Entity("QuestionsAndAnswers.DataLayer.Models.Roles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("QuestionsAndAnswers.DataLayer.Models.SoftwareName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SoftName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("softwareNames");
                });

            modelBuilder.Entity("QuestionsAndAnswers.DataLayer.Models.QuestionsAnswers", b =>
                {
                    b.HasOne("QuestionsAndAnswers.DataLayer.Models.SoftwareName", "SoftwareName")
                        .WithMany()
                        .HasForeignKey("SoftwareNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SoftwareName");
                });
#pragma warning restore 612, 618
        }
    }
}
